max_length_name: 50
max_length_mail: 255
min_length_pass: 6
min_length_phone: 10
max_length_phone: 11
max_length_add: 80
max_length_title: 100
max_length_rank: 255
max_length_lang: 255
max_length_career: 255
max_length_target: 500
max_length_level: 255
max_length_experience: 800
max_length_description: 2000
max_length_content: 800
max_length_noti: 500
max_length_tag: 15
per_sheet: 6
size_avatar: 5
