max_length_name: 50
max_length_mail: 255
min_length_pass: 6
min_length_phone: 10
max_length_phone: 11
max_length_address: 80
max_length_title: 100
max_length_rank: 255
max_length_lang: 255
max_length_career: 255
max_length_target: 500
max_length_level: 255
max_length_experience: 800
max_length_description: 2000
max_length_content: 800
max_length_noti: 500
max_length_tag: 15
per_sheet: 6
size_avatar: 5
age_from: 18
age_to: 60
per_sheet: 8
new_job: 10
size_avatar: 5000
avatar_medium: "300x300"
size_cv: 10
type_avatar: ["image/jpeg", "image/gif", "image/png"]
type_form: ["application/msword", "application/pdf", "application/zip"]
url_form: "public/system/:basename.:extension"
path_form: ":rails_root/public/system/:basename.:extension"

